language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env:
  - CRATE_VERSION=0.56.4
  - CRATE_VERSION=0.57.6
  - CRATE_VERSION=1.0.1

matrix:
  exclude:
    - jdk: openjdk7
      env: CRATE_VERSION=1.0.1
    - jdk: oraclejdk7
      env: CRATE_VERSION=1.0.1

cache:
  directories:
    - $HOME/.m2

sudo: false

script: ./gradlew test -s

notifications:
  email: false
